# example values

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
spring:
  datasource:
    url: jdbc:mysql:localhost:3306:maindatabase
    username: root
    password: Hd906betterr
  jpa:
    properties:
      hibernate.ddl-auto: none
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
