
spring.datasource.url: jdbc:mysql://localhost:3306/maindatabase
spring.datasource.username: root
spring.datasource.password: Hd906betterr
spring.jpa.hibernate.ddl-auto: update
indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox

